[package]
name = "stash"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
dirs   = "6.0.0"
clap   = { version = "4.5.41", features = ["derive"] }
serde  = { version = "1.0", features = ["derive"] }
toml   = "0.7"
